barrecode/urls.py
from django.contrib import admin
from django.urls import path, include
from  django.conf.urls.static import  static
from  django.conf import settings

admin.site.site_header = "STOCK"


urlpatterns = [
    path('admin/', admin.site.urls, name='admin', kwargs={'extra_context': {'title': 'Nouveau titre'}}),
    path('', include('stock.urls')),
    path('', include('athentication.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/urls.py
from django.urls import path
from . import views
from .views import ExportProductsCSVView, ExportProductsExcelView
from stock.views import SearchProductView

urlpatterns = [
    path('index', views.index, name='index'),
    path('acces_denied', views.acces_denied, name='acces_denied'),
    path('client', views.client, name='client'),
    path('add_client', views.add_client, name='add_client'),
    path('edit_client/<int:id>', views.edit_client, name='edit_client'),
    path('delete_client/<int:id>', views.delete_client, name='delete_client'),
    path('transport', views.transport, name='transport'),
     path('add_transport', views.add_transport, name='add_transport'),
    path('edit_transport/<int:id>', views.edit_transport, name='edit_transport'),
    path('delete_transport/<int:id>', views.delete_transport, name='delete_transport'),
    path('commande', views.commande, name='commande'),
    path('print_commande/<int:pk>', views.print_commande, name='print_commande'),
    path('print_commande2/<int:pk>', views.print_commande2, name='print_commande2'),
    path('livraison', views.livraison, name='livraison'),
    path('edit_livraison/<int:livraison_id>', views.edit_livraison, name='edit_livraison'),
    path('edit_livraison2/<int:livraison_id>', views.edit_livraison2, name='edit_livraison2'),
    path('suivi', views.suivi, name='suivi'),
    path('produit', views.produit, name='produit'),
    path('search_product/', SearchProductView.as_view(), name='search_product'),
    path('add_product', views.add_product, name='add_product'),
    path('produit/edit_product/<int:id>', views.edit_product, name='edit_product'),
    path('produit/delete_product/<int:id>', views.delete_product, name='delete_product'),
    path('export/csv/', ExportProductsCSVView.as_view(), name='export_products_csv'),
    path('export/excel/', ExportProductsExcelView.as_view(), name='export_products_excel'),
    path('stock_in', views.stock_in, name='stock_in'),
    path('operation_print/<int:id>', views.operation_print, name='operation_print'),
    path('stock_barre', views.stock_barre, name='stock_barre'),
    path('add_stock', views.add_stock, name='add_stock'),
    path('niveau', views.niveau, name='niveau'),
    path('create_n1', views.create_n1, name='create_n1'),
    path('niveau/edit_n1/<int:id>', views.edit_n1, name='edit_n1'),
    path('create_n2', views.create_n2, name='create_n2'),
    path('niveau/edit_n2/<int:id>', views.edit_n2, name='edit_n2'),
    path('create_n3', views.create_n3, name='create_n3'),
    path('niveau/edit_n3/<int:id>', views.edit_n3, name='edit_n3'),
    path('create_n4', views.create_n4, name='create_n4'),
    path('niveau/edit_n4/<int:id>', views.edit_n4, name='edit_n4'),
    path('create_n5', views.create_n5, name='create_n5'),
    path('niveau/edit_n5/<int:id>', views.edit_n5, name='edit_n5'),
]

stock/models.py
from django.db import models
import barcode
from barcode import Code128
from barcode.writer import ImageWriter
from io import BytesIO
from django.core.files import File
from phonenumber_field.modelfields import PhoneNumberField
import datetime



class Niveau1(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name="Niveau 1")
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)
    def __str__(self):
        return self.name
    
    
class Niveau2(models.Model):
    name = models.CharField(max_length=100)
    niveau1 = models.ForeignKey(Niveau1, null=True, blank=True, verbose_name="Niveau 2", on_delete=models.CASCADE, related_name='niveau2')
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name
    
    
class Niveau3(models.Model):
    name = models.CharField(max_length=100)
    niveau2 = models.ForeignKey(Niveau2, null=True, blank=True, verbose_name="Niveau 3", on_delete=models.CASCADE, related_name='niveau3')
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name
    
    
class Niveau4(models.Model):
    name = models.CharField(max_length=100)
    niveau3 = models.ForeignKey(Niveau3, null=True, blank=True, verbose_name="Niveau 4", on_delete=models.CASCADE, related_name='niveau4')
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name
    
    

class Niveau5(models.Model):
    name = models.CharField(max_length=100)
    niveau4 = models.ForeignKey(Niveau4, null=True, blank=True, verbose_name="Niveau 5", on_delete=models.CASCADE, related_name='niveau5')
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)


    def __str__(self):
        return self.name
    


class Client(models.Model):
    rasion_sociale = models.CharField(max_length=100, null=True, blank=True)
    nom_prenom = models.CharField(max_length=100, null=True, blank=True)
    adresse = models.TextField(null=True, blank=True)
    phone_number = PhoneNumberField(unique=True, null=True, blank=True, verbose_name="Numero de téléphone")
    email = models.EmailField(null=True, blank=True)
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.rasion_sociale
    
    
class Transporteur(models.Model):
    name_transp = models.CharField(max_length=100, null=True, blank=True, verbose_name="Nom entreprise")
    coordonn1 = models.CharField(max_length=100, null=True, blank=True, verbose_name="coordonnée 1")
    coordonn2 = models.CharField(max_length=100, null=True, blank=True, verbose_name="coordonnée 2")
    type_trans = models.CharField(max_length=100, null=True, blank=True, verbose_name="Type de livraison")
    phone_number = PhoneNumberField(unique=True, null=True, blank=True, verbose_name="Numero de téléphone")
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)
    
    def __str__(self):
        return self.name_transp
    
class Product(models.Model):
    code = models.CharField(max_length=100, null=True, blank=True, unique=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    stock = models.IntegerField()
    sous_contenaire = models.ForeignKey(Niveau5, null=True, blank=True, on_delete=models.CASCADE)
    description = models.TextField()
    barcode = models.FileField(upload_to='barcode', blank=True)
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)
    

    def __str__(self):
            return self.name
    
    
    def save(self, *args, **kwargs):
        Code128 = barcode.get_barcode_class('Code128')
        ean = Code128(f'{self.code}-{self.sous_contenaire.name}', writer=ImageWriter())
        buffer = BytesIO()
        ean.write(buffer)
        self.barcode.save(f'{self.name}{self.code}.png', File(buffer), save=False)
        return super().save(*args, **kwargs)



class Operation(models.Model):
    products = models.ManyToManyField(Product, through='LigneOperation')
    fournisseur = models.ForeignKey(Client, verbose_name='Fournisseur', on_delete=models.CASCADE, null=True, blank=True)
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.product.name
    


class LigneOperation(models.Model):
    product = models.ForeignKey(Product, verbose_name='produit', on_delete=models.CASCADE)
    operation = models.ForeignKey(Operation, null=True, blank=True, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)
    
    def __str__(self):
        return self.product.code
    
class Commande(models.Model):
    num_commande = models.CharField(unique=True, max_length=100, null=True, blank=True)
    articles = models.ManyToManyField(Product, through='LigneCommande')
    client = models.ForeignKey(Client, null=True, blank=True, on_delete=models.CASCADE)
    date_commande = models.DateField(null=True, blank=True)
    adresse_livraison = models.TextField(null=True, blank=True)
    transport = models.ForeignKey(Transporteur, null=True, blank=True, on_delete=models.CASCADE)
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.num_commande
    
    
class LigneCommande(models.Model):
    article = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE)
    commande = models.ForeignKey(Commande, null=True, blank=True, on_delete=models.CASCADE)
    quantite = models.PositiveIntegerField()
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)


class Livraison(models.Model):
    num_livraison = models.CharField(unique=True, max_length=100, null=True, blank=True)
    commande = models.ForeignKey(Commande, null=True, blank=True, on_delete=models.CASCADE)
    date_livaison = models.DateField(null=True, blank=True)
    livre = models.BooleanField(default=False)
    create_at = models.DateField(auto_now_add=True, null=True, blank=True)


    def __str__(self):
        return self.num_livraison
    

templates/base.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load django_htmx %}


<!DOCTYPE html>
<html>

<!--   Entête des methadonnées   -->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="shortcut icon" href="{% static 'images/app_img/favicon.ico' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'images/app_img/favicon.ico' %}" type="image/x-icon">
  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" type="text/css" href={% static "css/bootstrap.min.css"%}>
  <link rel="stylesheet" type="text/css" href={% static "DataTables/datatables.min.css"%}/>
  <!-- Our project just needs Font Awesome Free's Solid and Brand files -->
  <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
  <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
  <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
  <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>
  <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
  <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <!-- jquery cdn and js  local files -->
  <script src="{% static 'js/scripts.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <!-- Latest compiled and minified CSS --> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- Latest compiled JavaScript --> 
  <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
  {% block style %}
  <style>
	/* Style du spinner */
	.loader {
		border: 16px solid #f3f3f3;
		border-top: 16px solid #3498db;
		border-radius: 50%;
		width: 120px;
		height: 120px;
		animation: spin 2s linear infinite;
		position: fixed;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		z-index: 9999;
		display: none;
	}

	/* Animation du spinner */
	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}
</style>
{% endblock %}
  </head>
<body>
	<div class="loader"></div>
	{% block navb %}
	<!-------------Menu lateral gauche-------------------->
	<div class="row bg-info mb-0 h-10">
		<div class="dropdown dropstart">
			<button class="btn btn-white dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
				<i class="fa-solid fa-user text-white"></i>
				<span class="text-white font-italic font-weight-bold">{{request.user}}</span>
			</button>
			<ul class="dropdown-menu bg-info">
				<li><a class="dropdown-item bg-info text-white font-italic font-weight-bold" href="{% url 'change_password' %}">changer son mot de passe</a></li>
				<li><a class="dropdown-item bg-info text-white font-italic font-weight-bold" href="{% url 'logout_user' %}">logout</a></li>
			</ul>
		</div>
	</div>
		<div class="container-fluid">
			<div class="row flex-nowrap">
				<div class="col-auto col-md-3 col-xl-2 px-sm-2 bg-dark">

					<div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 min-vh-100">
						<ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
							<li class="nav-item">
								<a href="{% url 'index' %}" class="nav-link align-middle px-0">
									<i class="fas fa-house text-white"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Home</span>
								</a>
							</li>
							{% if perms.stock.view_niveau1 %}
							<li class="nav-item">
								<a href="{% url 'niveau' %}" class="nav-link align-middle px-0">
									<i class="fas fa-cart-plus text-white"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Niveau de stockage</span>
								</a>
							</li>
							{% endif %}
							{% if perms.stock.view_client %}
							<li class="nav-item">
								<a href="{% url 'client' %}" class="nav-link align-middle px-0">
									<i class="fas fa-user text-white"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Client</span>
								</a>
							</li>
							{% endif %}
							{% if perms.stock.view_transporteur %}
							<li class="nav-item">
								<a href="{% url 'transport' %}" class="nav-link align-middle px-0">
									<i class="fas fa-car text-white"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Transporteur</span>
								</a>
							</li>
							{% endif %}
							{% if perms.stock.view_product %}
							<li class="nav-item">
								<a href="{% url 'produit' %}" class="nav-link align-middle px-0">
									<i class="fa-solid fa-newspaper text-white"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Article</span>
								</a>
							</li>
							{% endif %}
							{% if perms.stock.view_operation %}
							<li class="nav-item">
								<a href="{% url 'stock_in' %}" class="nav-link align-middle px-0">
									<i class="fa-solid fa-arrow-trend-up text-white"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Provisions</span>
								</a>
							</li>
							{% endif %}
							{% if perms.stock.view_product %}
							<li class="nav-item">
								<a href="{% url 'stock_barre' %}" class="nav-link align-middle px-0">
									<i class="fa-solid fa-eye text-white"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Lecture</span>
								</a>
							</li>
							{% endif %}
							{% if perms.stock.view_commande %}
							<li class="nav-item">
								<a href="{% url 'commande' %}" class="nav-link align-middle px-0">
									<i class="fa-solid fa-server text-white"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Commande</span>
								</a>
							</li>
							{% endif %}
							{% if perms.stock.view_livraison %}
							<li class="nav-item">
								<a href="{% url 'livraison' %}" class="nav-link align-middle px-0">
									<i class="fa-solid fa-car text-white"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Livraison</span>
								</a>
							</li>
							{% endif %}
							{% if perms.stock.view_livraison %}
							<li class="nav-item">
								<a href="{% url 'suivi' %}" class="nav-link align-middle px-0">
									<i class="fa-solid fa-map text-success"></i> <span class="ms-1 d-none d-sm-inline text-white font-italic font-weight-bold">Suivi</span>
								</a>
							</li>
							{% endif %}
							
							{% comment %} <li>
								<a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
									<i class="fas fa-link text-white"></i> <span class="ms-1 d-none d-sm-inline text-white">Gestion</span> </a>
								<ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
									<li class="w-100">
										<a href="" class="nav-link px-0"> <i class="fas fa-car text-white"></i><span class="d-none d-sm-inline text-white">Niveau de stockage</span> </a>
									</li>
								</ul>
							</li>  {% endcomment %}
						</ul>
					</div>
				</div>
        {% endblock navb %}
				<div class="col py-3">
			
					{% block main %} 

					{% block search %}
					
					{% endblock search %}
					
					{% endblock main %}


				</div>
			</div>
		</div>

        
    {% block footer %}
    <div class="container shadow-lg bg-body-tertiary rounded">
      <footer class="py-1">
        <div class="d-flex flex-column flex-sm-row justify-content-between py-1 my-1 border-top border-success border-5">
          <p class="text-secondary font-weight-bold font-italic">&copy; {% now "D-d-M-Y" %} Company, Inc. All rights reserved</p>
          <ul class="list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-facebook" style="font-size: 100%; color: blue;"></i></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-twitter" style="font-size: 100%; color: yellowgreen;"></i></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-whatsapp" style="font-size: 100%; color: green;"></i></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><i class="fa-brands fa-linkedin" style="font-size: 100%; color: bluesky;"></i></a></li>
          </ul>
        </div>
      </footer>
    </div>
    {% endblock footer %}

<script src="{% static 'js/htmx.min.js' %}" defer></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<!-- bootstrap5 js--> 
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
 <!-- jquery--> 
 <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<!-- Datatables JS static --> 
<script type="text/javascript" src="{% static 'DataTables/datatables.min.js' %}"></script>
<!-- Datatables JS cdn -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs5/jq-3.6.0/jszip-2.5.0/dt-1.12.1/b-2.2.3/b-html5-2.2.3/b-print-2.2.3/datatables.min.js"></script> 

{% django_htmx_script %}


<script>
	var loader = document.querySelector(".loader");

	function showLoader() {
		loader.style.display = "block";
	}

	function hideLoader() {
		loader.style.display = "none";
	}

	document.addEventListener("DOMContentLoaded", function() {
		showLoader();
	});

	window.addEventListener("load", function() {
		hideLoader();
	});
</script>

</body>
</html>